version: '3'
services:
  api:
    build:
      context: ./app/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket for Docker in Docker
    ports:
      - "3000:3000"