AWSTemplateFormatVersion: 2010-09-09

Parameters:
  domainName:
    Type: String
    Default: stage.jur.onl

Resources:
  sslCert:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref domainName
      DomainValidationOptions:
        - DomainName: !Ref domainName
          ValidationDomain: !Ref domainName
      ValidationMethod: DNS
