name: Deploy JNL to S3 for static hosting
on: [ push ]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.3'

      - name: Install dependencies
        working-directory: ./web
        run: npm i

      - name: Build
        working-directory: ./web
        run: npm run build

      - name: Deploy Frontend
        uses: reggionick/s3-deploy@v3
        if: github.ref == 'refs/heads/master'
        with:
          folder: ./web/build
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ap-southeast-2
          dist-id: EGCMBVUN0OYSF
          invalidation: /*

      - name: Build and Deploy Backend
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        working-directory: ./app
        run: sh update.sh jnl-app
        env:
          AWS_DEFAULT_REGION: us-east-1